### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'address'

### ISSUE THREAD

**Issue by robiecz** [grain111/candela_test#1]
Hi, thx for another try!
But unfortunately there is a bug. (HASS 2022.10.0)

**Comment by grain111** [comment]
Did it work on 2022.9?
Do you have Bluetooth integration enabled? 
Did you remove any other integration that could be connected to Candela? 
Did you reset the Candela light (pinhole at the bottom of the device)? 
Did you include the configuration in your configuration.yaml and replaced MAC with address specific to your light? 
Could you post the whole trace?

**Comment by Gerrett84** [comment]
I have the same issue. 
- Bluetooth Integration isn't enabled
- no other integration is connected to candela
- Reset doesn't helped
- replaced the "MAC" with address from candela 

Error Log:
2022-10-06 18:26:52.155 ERROR (MainThread) [homeassistant.components.light] Error while setting up candela_test platform for light
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 281, in _async_setup_platform
await asyncio.shield(task)
File "/config/custom_components/candela_test/light.py", line 47, in async_setup_platform
async_add_entities([CandelaLight(device, light["name"])])
File "/config/custom_components/candela_test/light.py", line 55, in __init__
self._mac = device.address
AttributeError: 'NoneType' object has no attribute 'address'

**Comment by grain111** [comment]
Bluetooth integration should be enabled and configured.

**Comment by grain111** [comment]
When I get back home I will try to update Home Assistant to 2022.10 and check if it still works, because right now with this code it is working for me.

**Comment by Gerrett84** [comment]
Ok, after I enabled the Bluetooth integration, the error is gone. I was able to turn on the candela now.  Then there was only one connection error.

Logger: custom_components.candela_test.candela_v2
Source: custom_components/candela_test/candela_v2.py:303
Integration: candela_test
First occurred: 15:31:53 (7 occurrences)
Last logged: 15:42:29

Connection: BleakError: F8:24:41:C0:B0:1C - /org/bluez/hci0/dev_F8_24_41_C0_B0_1C: Failed to connect: [org.bluez.Error.Failed] Software caused connection abort
Send Cmd: BleakError: [org.bluez.Error.Failed] Not connected
Send Cmd: BleakError: Not connected

**Comment by grain111** [comment]
Could you try reseting Candela and restarting your Home Assistant?

**Comment by grain111** [comment]
For me it still works on 2022.10

**Comment by grain111** [comment]
> Ok, after I enabled the Bluetooth integration, the error is gone. I was able to turn on the candela now.  Then there was only one connection error.
> 
> Logger: custom_components.candela_test.candela_v2
> Source: custom_components/candela_test/candela_v2.py:303
> Integration: candela_test
> First occurred: 15:31:53 (7 occurrences)
> Last logged: 15:42:29
> 
> Connection: BleakError: F8:24:41:C0:B0:1C - /org/bluez/hci0/dev_F8_24_41_C0_B0_1C: Failed to connect: [org.bluez.Error.Failed] Software caused connection abort
> Send Cmd: BleakError: [org.bluez.Error.Failed] Not connected
> Send Cmd: BleakError: Not connected

I had the same error some time after update, but a restart helped.
Is it working for you?

**Comment by Gerrett84** [comment]
> > Ok, after I enabled the Bluetooth integration, the error is gone. I was able to turn on the candela now.  Then there was only one connection error.
> > Logger: custom_components.candela_test.candela_v2
> > Source: custom_components/candela_test/candela_v2.py:303
> > Integration: candela_test
> > First occurred: 15:31:53 (7 occurrences)
> > Last logged: 15:42:29
> > Connection: BleakError: F8:24:41:C0:B0:1C - /org/bluez/hci0/dev_F8_24_41_C0_B0_1C: Failed to connect: [org.bluez.Error.Failed] Software caused connection abort
> > Send Cmd: BleakError: [org.bluez.Error.Failed] Not connected
> > Send Cmd: BleakError: Not connected
> 
> I had the same error some time after update, but a restart helped. Is it working for you?

Yep, after a reboot it's working. Thanks
